name: 'action-rl-scanner'
author: 'Maarten Boot'
description: 'Apply reversinglabs/rl-scanner and upload report, show and return status'

branding:
  icon: 'check'
  color: 'green'

inputs:
  artifact-to-scan:  # id of input
    description: 'The file artifact we will be scanning (a file path relative to the workspace)'
    required: true

outputs:
  descripion:
    description: 'The result of the action: a string terminanting in FAIL or PASS'
    # value: ${{ steps.random-number-generator.outputs.random-number }}
  status:
    description: 'The single word result of the action: success, failure or error'
    # value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    # -------------------------------------------
    - name: show the input
      run: |
        ls -l ${{ inputs.artifact-to-scan }}
      shell: bash

    # -------------------------------------------
    - name: scan the file
      uses: docker://reversinglabs/rl-scanner
      with:
        entrypoint: /bin/bash
        args: ls -l >>$GITHUB_OUTPUT

    # -------------------------------------------
    - name: show the input
      run: |
        docker run --rm hello-world
      shell: bash
    # -------------------------------------------
    - name: show the input
      run: |
        docker build -t aaabbbccc .
      shell: bash
